name: Linting

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - uses: actions/cache@v3
      id: cache-node
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        path: |
          node_modules
          ~/.cache
          ~/.npm
    - name: npm install
      run: npm ci
    - name: eslint
      run: npm run lint:js
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: WPCS check
      uses: 10up/wpcs-action@stable
      with:
        standard: 'WordPress'
